from server import mcp
from utils.generate_report import generate_confluence_page

@mcp.tool()
def generate_confluence_report_tool(report: str, title: str) -> str:
    """
    This tool takes the report generated by Claude to generate a detailed HTML report
    for publishing to Confluence.
    Args:
        report (str): Report generated by Claude from result of run_sql_query_tool tool.
        title (str): The title of the report

    Returns:
        str: Message confirming confluence page creation
    """
    try:
        response = generate_confluence_page(report, title)
        return response
    except Exception as e:
        return f"Error: {str(e)}"